"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
#import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4m0=tb(t1vqm(m8$m1sum#pz@x$&(@$bvk_t!7&39h=mo*#r)&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'api',
    'corsheaders',
    'rest_framework.authtoken',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",

    "https://jegnus.co.uk",
    "https://jegnus.com",

]

CSRF_TRUSTED_ORIGINS = [
                        "https://jegnus.co.uk",
                        "https://jegnus.com",
                        ]

ROOT_URLCONF = 'djangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'd6r0jclvbt91c5',
        'USER': 'yhedtdrokgkmgs',
        'PASSWORD': 'f71107f0ea58b068c44916f40466bec7d256ac0b1451ec3d63c4a01895c94a13',
        'HOST': 'ec2-34-195-69-118.compute-1.amazonaws.com',
        'PORT': '5432',
    }
}
'''


DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'postgres',
    #     'USER': 'postgres',
    #     'PASSWORD': 'z23z2I3wMoEqClji',
    #     'HOST': '/cloudsql/falcon-337809:europe-west2:falcondatabase',
    #     'PORT': '5432',
    # },

    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'd6r0jclvbt91c5',
    #     'USER': 'yhedtdrokgkmgs',
    #     'PASSWORD': 'f71107f0ea58b068c44916f40466bec7d256ac0b1451ec3d63c4a01895c94a13',
    #     'HOST': 'ec2-34-195-69-118.compute-1.amazonaws.com',
    #     'PORT': '5432',
    # },
    #
     'default': {
         'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
         'USER': 'postgres',
         'PASSWORD': 'z23z2I3wMoEqClji',
        'HOST': '127.0.0.1',
         'PORT': '5432',
     },
    #.\cloud_sql_proxy.exe -instances="falcon-337809:europe-west2:falcondatabase"=tcp:5432

}




#---------------------------------Auth------------------------------------------




JWT_AUTH = {
    'JWT_PAYLOAD_GET_USERNAME_HANDLER':
        'auth0authorization.utils.jwt_get_username_from_payload_handler',
    'JWT_DECODE_HANDLER':
        'auth0authorization.utils.jwt_decode_token',
    'JWT_ALGORITHM': 'RS256',
    'JWT_AUDIENCE': 'https://dev-yxtqi7bm.us.auth0.com/api/v2/',
    'JWT_ISSUER': 'dev-yxtqi7bm.us.auth0.com/',
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
}


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# -----------Cloudinary________#
'''
cloudinary.config(
    cloud_name="dihbyzh3d",
    api_key="746152958597374",
    api_secret="SuDcNTHmc1mStM3HFPdSQx_t-nE",
    secure=True
)
'''
from google.oauth2 import service_account
GS_CREDENTIALS = service_account.Credentials.from_service_account_file(os.path.join(BASE_DIR,'cred.json'))


DEFAULT_FILE_STORAGE = 'djangoProject.gcloud.GoogleCloudMediaFileStorage'
GS_PROJECT_ID = 'falcon-337809'
GS_BUCKET_NAME = 'jegnus_images'
MEDIA_ROOT = "media/"
UPLOAD_ROOT = 'media/uploads/'
MEDIA_URL = 'https://storage.googleapis.com/{}/'.format( GS_BUCKET_NAME )




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_DIRS = [os.path.join(BASE_DIR, 'static')],
STATIC_URL = '/static/'



STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

